### ISSUE TITLE
Cannot get track listeners to work

### ISSUE THREAD

**Issue by MartinBspheroid** [lucianoiam/live_rpyc#1]
First of all, I gotta say that this is awesome! I was thinking about it as well, as making something custom in Ableton with LiveOSC became a nightmare. 

Seems like most of the functions work right out of the box, I can query what I need and command what I need as well. The only thing missing now is the callback to trigger actions via clips, but I cannot get it to work for some reason. 

Here's code I'm running as test case: 
 ```
  if __name__ == '__main__':

    Live = connect()
    live_app = Live.Application.get_application()
    song = live_app.get_document()

    def clipTestTriggered():
        print("huh ->clipTestTriggered ")
        
    def clipTestTriggered2():
        print("duh => clipTestTriggered")
    def tempoCallback ():
        print("temppooooo")
    def volumeCallback():
        print("yeah!")
    bind(song.add_tempo_listener, song.remove_tempo_listener, tempoCallback)
    bind(song.tracks[0].mixer_device.add_sends_listener, song.tracks[0].mixer_device.remove_sends_listener, volumeCallback)
    bind(song.tracks[0].add_clip_slots_listener, song.tracks[0].remove_clip_slots_listener,
        clipTestTriggered)

    for track in song.tracks:
        for clip in track.clip_slots:
            bind(clip.add_playing_status_listener, clip.remove_playing_status_listener, clipTestTriggered2)

    print('Connected to Ableton Live {}.{}.{}'.format(live_app.get_major_version(),
        live_app.get_minor_version(), live_app.get_bugfix_version()))
    print(song.tracks[0].mixer_device.sends_has_listener)
    start_thread()

    try:
        input('Try playing/pausing Live or press Enter to exit\n')
    except:
        pass

    disconnect()

```
So the code above spits out following: 

```
Connected to Ableton Live 10.1.7
<bound method MixerDevice.sends_has_listener of <MixerDevice.MixerDevice object at 0x0000000025514D48>>
Try playing/pausing Live or press Enter to exit
temppooooo
temppooooo
```
This is what I get when I start this one, mess around in Ableton with clips, and finally, fiddle with tempo.  
I'm not sure what is going on. Even if I try to add a listener to sends, it fails, even though it seems that it has a listener, according to that log. Do you have any idea what I might be doing wrong?

Cheers

**Comment by MartinBspheroid** [comment]
You are right. 

So, let me address all your points backward:

One would expect that `song.tracks[0].mixer_device.add_sends_listener` would add a listener to changes of the **send knobs** on the certain channel, not **addition/removal or return channels**. Geez, that's misleading and using this to sanity test another code at 4am is not cool idea. At all :)

Same goes for `song.tracks[0].add_clip_slots_listener`. Misleading, ehm....
So the code that seems to do the job is this: 

```
def addListeners():

    tracks = song.visible_tracks
    clipSlots = []
    for track in tracks:
        clipSlots.append(track.clip_slots)
    tracks = clipSlots
    for track in range(len(tracks)):
        for clip in range(len(tracks[track])):
            c = tracks[track][clip]            
            if c.clip != None:
                print(c.clip)
                add_cliplistener(c.clip, track, clip)

def clipCallback(clip, tid, cid):
    print(clip.name)
    print("Track " , tid)
    print("cid "  , cid)


def add_cliplistener(clip, tid, cid):
    cb = lambda :clipCallback(clip ,  tid ,  cid)
    if clip_listeners.has_key(clip) != 1:
        clip.add_playing_status_listener(cb)
        clip_listeners[clip] = cb

clip_listeners = {}
```
Which is a modified version of what is going [under the hood in here ](https://github.com/dinchak/LiveOSC/blob/04c5f2ae640b2d61dd6a6e87775a34acee8db366/LiveOSC.py#L408)

So this is really solving my issue.

Before I close this, I have to express my gratitude. I've been fiddling with API for a while and using different approaches for a past week, form node-liveosc, to just LiveOSC with typescript, to direct plain Python remote scripts. 
But this has proven to be the most reliable and FASTEST way to prototype and debug all I'm trying to do. Swiiiiiiiiiift! Fizzzzyyy!!! 👍 

Thank you. Keep it up!

**Comment by lucianoiam** [comment]
Hey thanks for the kind words! real credits go to people involved in some past Ableton hackaton https://github.com/bkillenit/AbletonAPI. I added polish, the observers helper and lots of testing.

Have fun!

**Comment by mark-zarandi** [comment]
@MartinBspheroid what would the BIND command look like though.  Thanks - MZ
