### ISSUE TITLE
Device Activator

### ISSUE THREAD

**Issue by laimison** [lucianoiam/live_rpyc#2]
Hey,

First of all thanks for bringing this tool up.
It works well by reading various information from Ableton, but finding it hard to change something. I know that Ableton API is not documented officially so that's the main issue.

----

Anyone found a way to activate a Rack or Device?

![Screenshot 2022-02-20 at 21 46 33](https://user-images.githubusercontent.com/15680538/154861316-8c91a10f-90bd-4254-93ef-b64150489113.png)

It's called "Device Activator" in GUI, but I have found that property is `is_active` via API.

What I've got is this in `client.py`:

```
    print(str(song.tracks[0].devices[0]), str(song.tracks[0].devices[0].is_active))
```

it returns:

```
('<RackDevice.RackDevice object at 0x172c4b270>', 'False')
```

if I do

```
  song.tracks[0].devices[0].is_active = True
```

it says

```
AttributeError: can't set attribute
```

----

I'm looking at https://structure-void.com/PythonLiveAPI_documentation/Live10.1.19.xml and searching by "Live.RackDevice.RackDevice" and seems nothing is offered.

It's even not clear how to to find information in docs or google, by which phrase: "activator", "active", "mute" or even something else.

Any hint would be appreciated

**Comment by lucianoiam** [comment]
Hi, looks like `is_active` is read-only according to the docs: _Return __const__ access to whether this device is active_ 

I only worked with a small subset of the API and that was a while ago now, but I recall Python's `dir()` being useful for this. It will return all the available properties and methods from an object:

```Python
print(dir(song.tracks[0].devices[0]))
```

Unfortunately we're alone in the dark with this API, expect lots of trial & error and hackery...

**Comment by laimison** [comment]
Thanks mate for taking a look. Finally, I found a method. It was hidden in the `parameters`, in the first element of this list.
In addition to this, `value` should be used to assign it... So as you told, sometimes it feels like hacking. Anyway, this works perfectly!

On/off

```
song.tracks[0].devices[0].parameters[0].value = 1.0
song.tracks[0].devices[0].parameters[0].value = 0.0
```

**Comment by lucianoiam** [comment]
Some things might not be exposed at all, I recall being unable to control some aspects of the looper device and having to resort to an awful approach involving virtual MIDI ports.

Glad you found a solution .Just opened a "discussions" tab in the repo, feel free to continue there if needed.

Closing the issue now.

**Comment by laimison** [comment]
I use Applescript + `pyautogui` when something is not possible https://pyautogui.readthedocs.io/en/latest . Of course, those actions disturb graphical interface/live situation for a short moment.

Please feel free to post an issue if you have something in the future. I watch this repo. An extra eyes, could be helpful sometimes.
